### ISSUE TITLE
Tests complete but the instance never finishes

### ISSUE THREAD

**Issue by gavocanov** [raniejade/spek-idea-plugin#13]
When running Spek tests all tests are finished but the tests executor thread never exits, visible in the screenshot.

This happens to me when running tests in IDEA 2016.2.4,
Kotlin: Version: 1.0.4-release-IJ2016.1-112
Spek plugin version: Version: 0.2.5
Tests dependencies:
```
        <junit-platform.version>1.0.0-M2</junit-platform.version>
        <spek.version>1.0.89</spek.version>

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-runner</artifactId>
            <version>${junit-platform.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>${junit-platform.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.spek</groupId>
            <artifactId>spek-api</artifactId>
            <version>${spek.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.spek</groupId>
            <artifactId>spek-junit-platform-engine</artifactId>
            <version>${spek.version}</version>
            <scope>test</scope>
        </dependency>
```
![screen shot 2016-10-10 at 10 37 36](https://cloud.githubusercontent.com/assets/1512839/19229392/d7a97fa8-8ed5-11e6-8d12-c58a9a2069d9.png)

Let me know if you need more info.

**Comment by raniejade** [comment]
Can you include the test source? Would really help the investigation.

**Comment by gavocanov** [comment]
Will try to create a simple case, that exact one is proprietary so....
But it behaves like that for every spec I have, using SubjectSpek<T>, maybe that's causing trouble?

**Comment by gavocanov** [comment]
Hi,

Tried to reproduce this and with normal stuff it works ok, it was a problem with my code, very sorry for bothering you.
