### ISSUE TITLE
"Include parent environment variables" default does not work & does not persist 

### ISSUE THREAD

**Issue by moikarin** [raniejade/spek-idea-plugin#35]
Run -> Edit Configurations ... -> Defaults -> Spek
Click ... (three dots icon) on the "Environment variables" settings
Check "Include parent environment variables"
Click OK
Click OK in parent dialog (Run/Debug Configurations)

Problem 1: running a Spek test creates new run config that does NOT have 'Include parent environment variables' checked.
Problem 2: quit Intellij -> start Intellij. The settings does not persist in the defaults.

Spek plugin 0.3.4
IntelliJ IDEA Ultimate 2017.1.1 / Build #IU-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

**Comment by uchuhimo** [comment]
I meet exactly same problem on Windows.

Environment:
Spek plugin: 0.3.4
IntelliJ IDEA Ultimate 2017.1.4 / Build #IU-171.4694.23, built on June 6, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0.15063

**Comment by raniejade** [comment]
Included in the `0.3.5` release, please update and let me know if the issue is still there.

**Comment by moikarin** [comment]
All good now in 0.3.5. Thank you!

**Comment by uchuhimo** [comment]
Thank you for fixing the issue!
