### ISSUE TITLE
Compilation Issues and Questions

### ISSUE THREAD

**Issue by gajwani** [raniejade/spek-idea-plugin#43]
Hi @raniejade,

We were trying to add some features to this plugin but didn't have an easy time getting it to compile.

We're wondering if you could add some instructions for how to build this from scratch in IntelliJ . We eventually hacked something together to build the project on our local machine, but aren't sure whether the process we used is the same as yours.

In getting the plugin to run we needed to fix at least one showshopper issue (#42) but we also had to muck around with the `profiles` in `plugins/build.gradle` but we're not sure how necessary that is in the general case.

When you build the project on your machine, does IntelliJ create an `.iml` file associated with it? Can you check that `.iml` into the repo? Without an IML file, we weren't able to get IntelliJ to recognize the repo as a plugin, and so we couldn't get a development workflow with a debugger going.

/cc @tjgrathwell

**Comment by raniejade** [comment]
I'm importing it in IntelliJ IDEA as a normal gradle project. I really don't like committing IDE specific files into the repo. To test the plugin you need run:

```
./gradlew plugin:runIdea -Pprofile=<profile>
```

For profile I would normally use `idea2016`, you could also use `local` to use a local installation (I use it to test the plugin against Android Studio) but be sure to update `plugin/build.gradle` to point to your actual local installation. 

I'll update the README to include the build instructions. Thanks for the contribution, btw!

**Comment by gajwani** [comment]
Thanks for the (future) updates to the README! 

Separately, how often do you republish this plugin? I would love to have the test-run feature available widely for others at our office to also use. :)

**Comment by raniejade** [comment]
@gajwani I'll do it this weekend. Development for the plugin has been halted for the moment, busy with personal stuff and also currently working on new stuff for Spek.

**Comment by gajwani** [comment]
@raniejade That's wonderful! I don't mean to hurry you. If there is anything I can do to help, let me know. Thanks for this plugin and all the new Spek features!

**Comment by raniejade** [comment]
`v0.3.5` is out now and I've also updated the README to include development instructions.
