### ISSUE TITLE
Run tests in folder not working properly when running in Android Studio 3.0

### ISSUE THREAD

**Issue by Rosomack** [raniejade/spek-idea-plugin#57]
When right-clicking a folder and clicking `Run tests in <package>` it runs all the tests in the module, should run the ones in the selected package exclusively. This is a mixed JUnit4 / Spek module but it all runs on JUnit 5.

The same thing happens in Android modules with JUnit4 / Spek tests.

Not sure where I should file this bug - is it against this project or one of the JUnit 5 components?

**Comment by raniejade** [comment]
It also runs JUnit X tests?

**Comment by Rosomack** [comment]
Correct, it runs all the JUnit 4 tests and all Spek tests it can find in the module instead of only the ones in the folder I point it to.

**Comment by raniejade** [comment]
Just noticed `Run tests in <package>` is managed by JUnit plugin not by spek's plugin. `Run specs in <package>` is the correct action. Sorry for the delays, busy week. I'm closing the issue now, re-open if I miss something.
