### ISSUE TITLE
spek plugin hangs waiting for jvm to shut down threads

### ISSUE THREAD

**Issue by andaag** [raniejade/spek-idea-plugin#62]
Dynamodb embedded is a bit horrible (and hacky). The following delegate:
https://gist.github.com/andaag/ee02753549c910ba6ea5ad4b27262682
With this dependency: 
testCompile 'com.amazonaws:DynamoDBLocal:1.11.86' 

Works fine in gradle, but runs forever when running it through intellij with the spek plugin. (Tests green, but task has to be killed). The reason is that dynamodb embedded does not properly shut down all threads. Maybe the spek plugin can skip waiting for a graceful shutdown?

**Comment by raniejade** [comment]
Created a new ticket in the main repo, see https://github.com/spekframework/spek/issues/345.
