### ISSUE TITLE
Subfolders not taken into account

### ISSUE THREAD

**Issue by m-maillot** [raniejade/spek-idea-plugin#72]
When I run all tests in a folder (right click on folder > Run 'Spek tests in...'), the plugin does not run tests into subfolders. It runs only test at the root of this folder.

Spek version: `2.0.0`
Spek plugin: `2.0.0-rc.1.180+b8533a4-Studio3.3` and `2.0.0-Studio3.3`

Android Stuido: `Android Studio 3.3 Build #AI-182.5107.16.33.5199772`

**Comment by raniejade** [comment]
@m-maillot can you move this to https://github.com/spekframework/spek? This repo is for the spek1 IDE plugin,

**Comment by m-maillot** [comment]
It's already opened: https://github.com/spekframework/spek/issues/606 👍
